import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { z } from 'zod';

if (!process.env.LLM_API_KEY) {
  console.error('SparkIQ cannot start: add LLM_API_KEY to backend/.env.');
  process.exit(1);
}

const app = express();
app.use(cors());
app.use(express.json({ limit: '2mb' }));

const requestSchema = z.object({ stage: z.number().int().min(1).max(10), context: z.record(z.any()).default({}), userInput: z.string().optional() });
const stages = [
  'Discover Questions: return idea, description, ideaType, audience, goals, constraints, and a dynamic discoveryQuestions array of 4-10 brief questions. Always include the four required questions exactly: How did you come up with this idea?, Why this idea?, Who is it for?, What problem does it solve?. Add only the missing-gap questions appropriate to the clarity of the submitted idea. The description must explain the submitted idea in plain language, and include ideaContext on each question.',
  'Idea Improver: return three fresh suggestions with title, reason, impact, changed and whyChanged, accepted=false. Avoid every prior option supplied in context.previousOptions.',
  'Positioning: return category, differentiator, valueProposition, competitiveAngle, competitors, debate with strategist, skeptic and customer messages.',
  'Personality: return traits with justification, avoidTraits, and archetype with a one-line reason. Avoid every prior trait in context.previousOptions.',
  'Name + Tagline: return 4 names with rationale, tagline and oneLinePitch. Detect cliches and reject weak options. If a visual theme exists, match its mood. Avoid every prior name and tagline in context.previousOptions.',
  'Visual Direction: return palette with hex values, readable names, six alternative palettes, typography, logoStyle, shapes, imageStyle, avoid, poster copy, and six distinct posterSuggestions. Avoid prior poster directions in context.previousOptions.',
  'Brand Voice: return toneRules, doExamples, dontExamples, sampleMessages, voiceStyles for audio selection, and reflect context.brandValues.',
  'Video Script: return duration and scenes with timestamp, visual, voiceover and onScreenText, plus an audioTrack fallback description.',
  'Launch Content: return landingHeadline, oneLinePitch, instagram, linkedin and ecommerce guide, reflecting context.brandValues.',
  'Final Brand Kit: return a concise strategy summary, launch plan, scores with reasons, autofixes and consistencyScore.'
];

function seedResult(stage, context, userInput = '') {
  const idea = context.idea || userInput || 'a new venture';
  const lower = idea.toLowerCase();
  const food = /cake|bakery|food|cook|restaurant|bake/.test(lower);
  const audience = context.audience || (food ? 'people celebrating small, meaningful moments' : 'curious early adopters who value clarity');
  const name = food ? 'Crumb & Candle' : 'Northstar Signal';
  const palette = food ? [{ name: 'Deep Navy', hex: '#0A1128' }, { name: 'Cobalt Blue', hex: '#2E5EAA' }, { name: 'Silver Mist', hex: '#DDE6F5' }, { name: 'Apricot Glow', hex: '#F2A65A' }] : [{ name: 'Deep Navy', hex: '#0A1128' }, { name: 'Electric Blue', hex: '#3B82F6' }, { name: 'Silver Mist', hex: '#B8C4D9' }, { name: 'Signal Lime', hex: '#B8E05F' }];
  const previous = context.previousOptions || [];
  const base = { stage, generatedAt: new Date().toISOString(), reasoning: 'This recommendation connects the idea, audience, and desired emotional outcome while leaving room to validate market facts.' };
  const round = Number(context.regeneration || 0);
  if (stage === 1) { const detailed = idea.trim().split(/\s+/).length >= 10 && [/\bfor\b/i, /\bto\b/i, /\bfocused on\b/i, /\bin\b/i, /\bwith\b/i].filter(pattern => pattern.test(idea)).length >= 2; const requiredQuestions = ['How did you come up with this idea?', 'Why this idea?', 'Who is it for?', 'What problem does it solve?']; const gapQuestions = detailed ? ['Any goals or constraints?'] : ['Any goals or constraints?', 'What would the first version or offer include?', 'Which competitors or alternatives do people use today?', 'What budget, timeline, or scope do you have in mind?', 'What would make this idea successful in the first three months?']; const questionList = [...requiredQuestions, ...gapQuestions]; return { ...base, idea, description: `${idea} is an early-stage ${food ? 'food business' : 'product or service'} idea focused on creating a clear, useful experience for a specific audience. The first version should stay narrow enough to test, learn from real people, and improve before expanding.`, ideaType: food ? 'food business' : 'product or service', audience, goals: ['Validate demand', 'Earn repeat customers', 'Launch with a distinct point of view'], constraints: ['Small initial budget', 'Need proof before scaling'], discoveryQuestions: questionList.map(question => ({ question, required: true, ideaContext: `Answer briefly with the submitted idea in mind: “${idea}”`, answer: context.discoveryAnswers?.[question] || '', placeholder: 'In a sentence or two...' })), openQuestions: ['What is the first offer?', 'Which moment makes someone choose you?'], questionMode: detailed ? 'focused' : 'deep discovery' }; }
  if (stage === 2) { const rounds = [['Name the first use case', 'Choose a signature detail', 'Start with a narrow promise'], ['Package one celebration moment', 'Make the ordering ritual memorable', 'Test one premium proof point'], ['Own the birthday milestone', 'Turn customization into a signature', 'Build a referral-first launch']]; const titles = rounds[round % rounds.length]; return { ...base, suggestions: titles.map((title, index) => ({ title, reason: ['A concrete first moment makes the idea easier to test and remember.', 'One repeatable detail can become a recognizable brand asset.', 'Focus creates proof faster than trying to serve everyone.'][index], impact: ['Higher conversion', 'Stronger recall', 'Faster learning'][index], changed: round ? `Fresh alternative round ${round}` : 'Original direction', whyChanged: userInput && userInput !== idea ? `Refined around your direction: ${userInput}` : 'Grounded in the current audience and promise.', accepted: false })) }; }
  if (stage === 3) return { ...base, category: food ? 'celebration bakery' : 'trust-first digital tools', differentiator: food ? 'Small-batch cakes designed around the story of the celebration.' : 'Clear, calm tools that turn uncertainty into an actionable signal.', valueProposition: `For ${audience}, ${name} makes the important choice feel considered, simple, and worth sharing.`, competitiveAngle: 'Own the specific moment, not the whole market.', competitors: [{ name: 'Local alternative', status: 'AI-suggested, please verify' }, { name: 'Established category leader', status: 'AI-suggested, please verify' }, { name: 'DIY option', status: 'AI-suggested, please verify' }], debate: [{ agent: 'Strategist', message: 'Lead with a focused promise and a distinctive proof point.' }, { agent: 'Skeptic', message: 'The promise needs customer interviews and competitor verification before being treated as fact.' }, { agent: 'Customer', message: 'I want to understand quickly why this was made for my situation.' }] };
  if (stage === 4) { const traitRounds = [['Warm', 'Crisp', 'Generous'], ['Thoughtful', 'Playful', 'Reliable'], ['Inviting', 'Crafted', 'Bright']]; const selected = traitRounds[round % traitRounds.length]; return { ...base, traits: selected.map((item, index) => ({ name: item, reason: ['Makes the experience feel human.', 'Protects clarity when choices matter.', 'Turns customers into participants.'][index], rank: index + 1 })), archetype: { name: food ? 'The Caregiver' : 'The Sage', reason: 'It fits an audience looking for thoughtful help without pressure.' }, brandValues: food ? [{ name: 'Reliability', reason: 'Birthday customers need the cake and delivery to arrive as promised.' }, { name: 'Care', reason: 'Thoughtful details make a celebration feel personal.' }, { name: 'Joy', reason: 'The audience is buying an experience worth remembering.' }] : [{ name: 'Clarity', reason: 'People need confidence when choosing a new solution.' }, { name: 'Trust', reason: 'Reliable guidance lowers decision anxiety.' }, { name: 'Progress', reason: 'Small steps help the audience move forward.' }], avoidTraits: ['Corporate', 'Overly polished', 'Urgent or fear-driven'] }; }
  if (stage === 5) { const premium = context.themePreference === 'premium' || context.palette?.some(item => /0A1128|2E5EAA|3B82F6/i.test(item.hex)); const rounds = premium ? [['Cobalt Crumb', 'Blue Hour Bakehouse', 'Lumen Cake Co.', 'Northstar Sweets'], ['Velvet Oven', 'Azure Crumb', 'Halo Bakehouse', 'Midnight Sugar'], ['Crown & Crumb', 'Nova Bake Co.', 'Bluebell Atelier', 'Silver Spoon Cakes']] : [['Crumb & Candle', 'Little Ember', 'Wishwork', 'Sunday Spark'], ['Butter & Bloom', 'Gathered Cake Co.', 'Honeywish', 'Good Day Bakes'], ['Sugar Story', 'Merry Crumb', 'Kindred Cakes', 'The Birthday Table']]; const names = rounds[round % rounds.length]; return { ...base, names: names.map(item => ({ name: item, rationale: premium ? 'A polished, modern sound chosen to fit the premium visual direction.' : 'Balances a tangible cue with a memorable emotional one.', clicheCheck: 'Passed: avoids generic category words.' })), tagline: ['Make the moment delicious.', 'Bake a little more joy.', 'A beautiful reason to gather.'][round % 3], oneLinePitch: `A ${food ? 'small-batch celebration brand' : 'focused intelligence brand'} for people who want better moments, not more noise.`, rejectedCliches: ['Best', 'Hub', 'Solutions'], rejectedReasons: ['Overused and difficult to own without proof.'] }; }
  if (stage === 6) { const poster = { eyebrow: food ? 'SMALL BATCH / BIG MOMENTS' : 'A CLEAR SIGNAL', headline: context.name || name, subhead: food ? 'Make the moment delicious.' : 'Make the next move clearer.' }; const palettes = [palette, [{ name: 'Steel Blue', hex: '#172B4D' }, { name: 'Sky Signal', hex: '#6EA8FF' }, { name: 'Cloud White', hex: '#F0F4FA' }, { name: 'Coral Spark', hex: '#FF8364' }], [{ name: 'Ink Blue', hex: '#081526' }, { name: 'Royal Blue', hex: '#4267B2' }, { name: 'Frost', hex: '#C9D7EA' }, { name: 'Honey Accent', hex: '#E8B04E' }], [{ name: 'Harbor Blue', hex: '#12304A' }, { name: 'Mist Blue', hex: '#76A9C2' }, { name: 'Pearl', hex: '#E8EEF2' }, { name: 'Copper Light', hex: '#C9825A' }], [{ name: 'Night Steel', hex: '#101A2B' }, { name: 'Blue Steel', hex: '#405D7A' }, { name: 'Silver', hex: '#CBD5E1' }, { name: 'Ice Glow', hex: '#A7D8F0' }], [{ name: 'Royal Navy', hex: '#14213D' }, { name: 'Bright Cobalt', hex: '#2774E6' }, { name: 'Moon Silver', hex: '#D6E0ED' }, { name: 'Lime Signal', hex: '#B6D957' }]]; const chosenPalette = context.selectedPalette || palettes[round % palettes.length]; return { ...base, palette: chosenPalette, palettes: palettes.map((colors, index) => ({ id: String.fromCharCode(65 + index), name: `Palette ${String.fromCharCode(65 + index)}: ${['Midnight Steel', 'Ocean Breeze', 'Ink & Honey', 'Harbor Mist', 'Night Silver', 'Royal Signal'][index]}`, colors })), typography: { display: 'Space Grotesk', body: 'DM Sans' }, logoStyle: 'A compact wordmark with one precise spark or notch.', shapes: 'Rounded capsules paired with one sharp diagonal accent.', imageStyle: 'Close, tactile, natural light; show the real product or moment.', avoid: ['Stock-smile imagery', 'Overloaded gradients', 'Generic swooshes'], poster, posterStyle: context.posterStyle || 'minimal', posterSuggestions: [1, 2, 3, 4, 5, 6].map(number => ({ id: number, label: `Suggestion ${number}`, layout: `${['editorial', 'bold', 'gallery', 'side-aligned', 'pattern', 'icon-led'][number - 1]} variant ${round + 1}`, palette: chosenPalette, poster: { ...poster, eyebrow: `${poster.eyebrow} / ${(context.posterStyle || 'minimal').toUpperCase()} / ${number} / ${round + 1}` } })) }; }
  if (stage === 7) return { ...base, toneRules: ['Be warm before clever.', 'Use short concrete sentences.', 'Invite rather than pressure.'], doExamples: ['Your cake is ready for its big entrance.', 'Here is the clearest next step.'], dontExamples: ['We disrupt the industry.', 'Act now before it is too late.'], sampleMessages: ['A little spark for your big moment.', 'Made thoughtfully. Delivered simply.', 'Want to make this yours?'], valueMessages: context.brandValues?.map(value => `${value.name}: ${value.reason}`) || [], voiceStyles: [{ name: 'Warm Female', description: 'Friendly and intimate' }, { name: 'Confident Male', description: 'Measured and assured' }, { name: 'Energetic Youth', description: 'Bright and quick' }] };
  if (stage === 8) return { ...base, duration: '45 seconds', scenes: [{ timestamp: '0-06s', visual: 'A close-up of the first meaningful detail.', voiceover: 'Every good idea starts with a moment worth making better.', onScreenText: name }, { timestamp: '06-20s', visual: 'Founder shaping the offer for a real person.', voiceover: `That is why ${name} focuses on the detail others rush past.`, onScreenText: 'Made for the moment' }, { timestamp: '20-38s', visual: 'Customer experiencing the result.', voiceover: 'Simple to choose. Memorable to receive.', onScreenText: 'Make it count' }, { timestamp: '38-45s', visual: 'Wordmark and invitation.', voiceover: 'Make the next moment yours.', onScreenText: food ? 'Make the moment delicious.' : 'Make the next move clearer.' }], audioTrack: { status: 'ready', label: 'Script-synced voice-over audio track', voice: context.voiceStyle || 'Warm Female', note: 'Full visual video generation is a stretch feature; this audio track is ready for the script scenes.' } };
  if (stage === 9) return { ...base, landingHeadline: food ? 'Celebration, baked around you.' : 'Clarity for the move that matters.', oneLinePitch: food ? 'Small-batch cakes with a story in every detail.' : 'Focused intelligence for people building what is next.', instagram: `Built on ${context.brandValues?.map(value => value.name.toLowerCase()).join(', ') || 'care and clarity'}. A small spark can change the whole moment.`, linkedin: `Our launch is guided by ${context.brandValues?.map(value => value.name.toLowerCase()).join(', ') || 'care and clarity'}: a considered way to move from idea to action.`, ecommerce: food ? { channel: 'Test on Zepto or Blinkit after offline validation', listingTitle: `${name} celebration cakes`, description: 'Small-batch cakes made with care for the moments people remember.', keywords: ['birthday cake', 'small batch', 'celebration'], steps: ['Test the offer offline', 'Collect repeatable feedback', 'Then list online'] } : null };
  return { ...base, summary: `${name} is a focused brand for ${audience}.`, scores: [{ area: 'Name', uniqueness: 8, consistency: 9, reason: 'Distinctive image and aligned with the promise.' }, { area: 'Tagline', uniqueness: 8, consistency: 9, reason: 'Short, active, and emotionally specific.' }, { area: 'Logo direction', uniqueness: 7, consistency: 8, reason: 'Strong direction; logo uniqueness is an AI estimate, not a guarantee.' }, { area: 'Voice', uniqueness: 8, consistency: 9, reason: 'Warm clarity matches the audience.' }, { area: 'Visuals', uniqueness: 8, consistency: 9, reason: 'The palette balances trust with an owned accent.' }], autofixes: [], consistencyScore: 8.6 };
}

async function callModel(stage, context, userInput) {
  const prompt = `You are SparkIQ's ${stages[stage - 1]} Return ONLY valid JSON matching the requested structure. Use all prior brand context. Never invent competitor facts; mark suggestions for verification. Context: ${JSON.stringify(context)} User input: ${userInput || ''}`;
  const response = await fetch(`${process.env.LLM_BASE_URL || 'https://api.openai.com/v1'}/chat/completions`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${process.env.LLM_API_KEY}` }, body: JSON.stringify({ model: process.env.LLM_MODEL || 'gpt-4o-mini', temperature: 0.7, response_format: { type: 'json_object' }, messages: [{ role: 'system', content: 'You produce structured brand strategy JSON.' }, { role: 'user', content: prompt }] }) });
  if (!response.ok) throw new Error(`LLM request failed (${response.status})`);
  const data = await response.json();
  return JSON.parse(data.choices[0].message.content);
}

app.get('/api/health', (_req, res) => res.json({ ok: true, provider: process.env.LLM_MODEL || 'configured model' }));
app.post('/api/stage', async (req, res) => {
  const parsed = requestSchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: 'stage, context, and userInput are required' });
  const { stage, context, userInput } = parsed.data;
  try { return res.json({ data: await callModel(stage, context, userInput), source: 'llm' }); }
  catch (error) { return res.json({ data: seedResult(stage, context, userInput), source: 'local-fallback', warning: error.message }); }
});
app.post('/api/chat', async (req, res) => {
  const { message, context = {} } = req.body;
  try {
    const answer = await callModel(1, context, `Founder question: ${message || 'How do I begin?'} Answer as a concise, practical branding coach. Do not return JSON.`);
    return res.json({ answer: typeof answer === 'string' ? answer : JSON.stringify(answer) });
  } catch {
    return res.json({ answer: `Based on your current direction, keep the next decision focused on ${context.audience || 'a specific audience'} and test one promise in the real world. Your question was: “${message || 'How do I begin?'}”` });
  }
});
app.post('/api/share', (req, res) => res.json({ id: crypto.randomUUID(), url: 'http://localhost:5173/share/demo-brand-kit' }));

const port = process.env.PORT || 4000;
app.listen(port, () => console.log(`SparkIQ backend listening on http://localhost:${port}`));